name: CI/CD

on:
    push:
    pull_request:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        env:
            NODE_ENV: development

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Install dependencies
                run: npm ci

            -   name: Build
                run: npm run build

            -   name: Upload artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: dist
                    path: dist/
    test:
        name: Test
        runs-on: ubuntu-latest
        needs: build

        permissions:
            contents: read
            checks: write
            statuses: write

        env:
            NODE_ENV: development

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Install dependencies
                run: npm ci

            -   name: Test
                run: npm run coverage

            -   name: Upload coverage data
                uses: actions/upload-artifact@v3
                with:
                    name: coverage
                    path: coverage/

            -   name: Verify coverage
                uses: devmasx/coverage-check-action@v1.2.0
                with:
                    type: lcov
                    result_path: coverage/lcov.info
                    # Settle for nothing less!
                    min_coverage: 100
                    token: ${{ github.token }}
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: test
        if: github.ref_type == 'tag'

        env:
            NODE_ENV: development

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Download built files
                uses: actions/download-artifact@v4.1.7
                with:
                    name: dist
                    path: dist/

            -   name: Publish
                run: npm publish
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
